[project]
name = "hingesdk"
version = "0.1.0"
description="A Python SDK for the Hinge API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.5",
    "requests>=2.32.3",
]
